[package]
name = "git-flow-rs"
version = "0.4.3"
edition = "2021"
authors = ["niuiic <niuiicde@gmail.com>"]
keywords = ["git", "gitflow"]
license = "MIT"
homepage = "https://github.com/niuiic/git-flow.rs"
repository = "https://github.com/niuiic/git-flow.rs"
categories = ["command-line-utilities"]
description = "Extensible git flow written in rust."

[[bin]]
name = "git-flow"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
regex = "1.12"
anyhow = "1.0"
tokio = { version = "1.52", features = ["full"] }
clap = { version = "4.6", features = ["derive"] }
clap_complete = "4.6"
toml = "1.1"
tabled = "0.21"
terminal_size = "0.4"
git2 = "0.21"
